import streamlit as st
import joblib
import numpy as np
import pandas as pd

# ---------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------

st.set_page_config(
    page_title="Stacking Regressor Salary Prediction",
    page_icon="💰",
    layout="wide"
)

# ---------------------------------------------------
# DARK THEME STYLING
# ---------------------------------------------------

st.markdown("""
<style>

/* Main App */
.stApp {
    background-color: #0d1117;
    color: white;
}

/* Sidebar */
[data-testid="stSidebar"] {
    background-color: #161b22;
}

/* Sidebar Text */
[data-testid="stSidebar"] * {
    color: white !important;
}

/* Main Heading */
h1 {
    color: #58a6ff !important;
    text-align: center;
    font-weight: 700;
}

/* Sub Headings */
h2, h3 {
    color: #79c0ff !important;
}

/* Text */
p, li, label, span {
    color: #e6edf3 !important;
}

/* Buttons */
.stButton > button {
    width: 100%;
    background: linear-gradient(
        135deg,
        #238636,
        #2ea043
    );
    color: white;
    border-radius: 10px;
    border: none;
    font-size: 16px;
    font-weight: bold;
    padding: 10px;
}

.stButton > button:hover {
    background: #2ea043;
    color: white;
}

/* Tables */
table {
    border-radius: 10px;
    overflow: hidden;
}

/* Dataframe */
[data-testid="stDataFrame"] {
    background-color: #161b22;
    border-radius: 10px;
}

/* Footer */
.footer {
    text-align: center;
    color: #8b949e;
    font-size: 14px;
    margin-top: 20px;
}

</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------
# LOAD MODEL
# ---------------------------------------------------

model = joblib.load("stack_regressor.pkl")

# ---------------------------------------------------
# HEADER
# ---------------------------------------------------

st.markdown(
    "<h1>💰 Salary Prediction using Stacking Regressor</h1>",
    unsafe_allow_html=True
)

st.markdown("""
This project demonstrates **Stacking Ensemble Learning for Regression**.

### Base Learners
- Random Forest Regressor
- Support Vector Regressor (SVR)
- Gradient Boosting Regressor

### Meta Learner
- Linear Regression

The predictions generated by the base learners are used as inputs for the meta learner,
which produces the final salary prediction.
""")

# ---------------------------------------------------
# DATASET INFORMATION
# ---------------------------------------------------

with st.expander("📊 Dataset Information"):

    st.write("""
    This salary dataset contains information about employee experience
    and corresponding salary values.

    **Target Variable**
    - Salary

    **Input Feature**
    - Years of Experience
    """)

# ---------------------------------------------------
# SIDEBAR
# ---------------------------------------------------

st.sidebar.header("👨‍💼 Employee Information")

years_exp = st.sidebar.slider(
    "Years of Experience",
    min_value=0.0,
    max_value=20.0,
    value=5.0,
    step=0.1
)

# ---------------------------------------------------
# INPUT DISPLAY
# ---------------------------------------------------

st.subheader("📋 Input Details")

input_df = pd.DataFrame({
    "Feature": ["Years of Experience"],
    "Value": [years_exp]
})

st.table(input_df)

# ---------------------------------------------------
# PREDICTION
# ---------------------------------------------------

if st.button("🔍 Predict Salary"):

    input_data = np.array([[years_exp]])

    prediction = model.predict(input_data)

    st.success(
        f"💰 Predicted Salary: ₹ {prediction[0]:,.2f}"
    )

    # Celebration Effects
    st.balloons()
    st.toast("Prediction Generated Successfully 🎉")

# ---------------------------------------------------
# SAMPLE INSIGHTS
# ---------------------------------------------------

st.markdown("---")

st.subheader("📈 Expected Salary Trend")

salary_levels = {
    "0-2 Years": "Entry Level",
    "3-5 Years": "Junior Professional",
    "6-10 Years": "Mid-Level Professional",
    "10+ Years": "Senior Professional"
}

trend_df = pd.DataFrame(
    salary_levels.items(),
    columns=["Experience Range", "Career Level"]
)

st.table(trend_df)

# ---------------------------------------------------
# MODEL DETAILS
# ---------------------------------------------------

st.markdown("---")

st.subheader("⚙️ Model Architecture")

st.write("""
### Base Learners

1. Random Forest Regressor

2. Support Vector Regressor (SVR)

3. Gradient Boosting Regressor

### Meta Learner

Linear Regression

The meta learner combines the predictions of all base learners
to improve overall prediction accuracy.
""")

# ---------------------------------------------------
# HYPERPARAMETER TUNING
# ---------------------------------------------------

st.markdown("---")

st.subheader("🔧 Hyperparameter Tuning")

st.info("""
GridSearchCV was used for Hyperparameter Tuning.

Random Forest Parameters:
• n_estimators
• max_depth

SVR Parameters:
• C
• kernel

The best-performing models were selected and used
inside the Stacking Regressor.
""")

# ---------------------------------------------------
# PERFORMANCE METRICS
# ---------------------------------------------------

st.markdown("---")

st.subheader("📊 Evaluation Metrics")

st.write("""
The model performance was evaluated using:

• Mean Absolute Error (MAE)

• Root Mean Squared Error (RMSE)

• R² Score

These metrics help measure how accurately
the model predicts salary values.
""")

# ---------------------------------------------------
# ABOUT STACKING
# ---------------------------------------------------

st.markdown("---")

st.subheader("📚 About Stacking Ensemble Learning")

st.write("""
Stacking is an ensemble machine learning technique that combines
multiple machine learning models.

Instead of relying on a single model, stacking learns how to
combine the strengths of different models through a meta learner.

Benefits:

✔ Improved Accuracy

✔ Better Generalization

✔ Reduced Overfitting

✔ More Robust Predictions
""")

# ---------------------------------------------------
# FOOTER
# ---------------------------------------------------

st.markdown("---")

st.markdown(
    """
    <div class="footer">
        💰 Machine Learning Project | Stacking Regressor with Hyperparameter Tuning
    </div>
    """,
    unsafe_allow_html=True
)